<?php

namespace AppBundle\Repository;

/**
 * coursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coursesRepository extends \Doctrine\ORM\EntityRepository
{
    /**creatQueryBuilder : constructeur de requêtes
      *getQuery : execution de la requete /appel de cette methode en avant dernière position
      *getResult : renvoie un array d'objet
     **/
    function courseAlias()
    {
        $query = $this->createQueryBuilder('courseAlias')
	    ->select('courseAlias.name','courseAlias.slug')
        ->getQuery()
        ->getResult();

    return $query;
    }
}
